name: Python CICD using github actions

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  Dependency-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.3

      - name: Install dependencies with poetry
        run: |
          pip install poetry
      - name: Configure poetry
        run: poetry config virtualenvs.in-project true
      
      - name: Install dependencies with poetry
        run: poetry install

      - name: Code linting python
        run: |
          poetry run isort .
          poetry run black .
          poetry run autoflake --in-place --recursive --remove-unused-variables . 
          
      - name: Commit report
        run: |
          git config --global user.name 'Sobit Regmi'
          git config --global user.email 'regmi.sobit@gmail.com'
          git add .
          git commit --amend --no-edit
          git push -f



  
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . --file Dockerfile -t sobit_image

      - name: Test image
        run: docker run --rm -d --name sobit_container -p 8000:8000 sobit_image
